spec:
      containers:
      - name: arrows-ts-container
        # Azure Pipelines will overwrite this placeholder automatically
        image: placeholder-image-name 
        ports:
        - containerPort: 3000